<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>Python 入门 on KM的博客</title>
        <link>https://Ch-kaiming.github.io/tags/python-%E5%85%A5%E9%97%A8/</link>
        <description>Recent content in Python 入门 on KM的博客</description>
        <generator>Hugo -- gohugo.io</generator>
        <language>zh-cn</language>
        <copyright>kaiming space</copyright><atom:link href="https://Ch-kaiming.github.io/tags/python-%E5%85%A5%E9%97%A8/index.xml" rel="self" type="application/rss+xml" /><item>
        <title></title>
        <link>https://Ch-kaiming.github.io/p/</link>
        <pubDate>Mon, 01 Jan 0001 00:00:00 +0000</pubDate>
        
        <guid>https://Ch-kaiming.github.io/p/</guid>
        <description>&lt;h1 id=&#34;environmentnotwritableerror-the-current-user-does-not-have-write-permissions-to-the-targetenvironme---知乎&#34;&gt;EnvironmentNotWritableError: The current user does not have write permissions to the targetenvironme - 知乎
&lt;/h1&gt;&lt;blockquote&gt;
&lt;h2 id=&#34;excerpt&#34;&gt;Excerpt
&lt;/h2&gt;&lt;p&gt;一、pycharm安装第三方库报错（用pip也会报错） 错误原因，python虚拟环境base所在文件，没有给予user修改文件的权限。 二、解决办法： 1、找到base环境所在文件，右击选择“属性”，再点击“安全”。 如果不知道…&lt;/p&gt;
&lt;/blockquote&gt;
&lt;hr&gt;
&lt;h2 id=&#34;一pycharm安装第三方库报错用pip也会报错&#34;&gt;一、pycharm安装第三方库报错（用pip也会报错）
&lt;/h2&gt;&lt;p&gt;&lt;img src=&#34;https://Ch-kaiming.github.io/EnvironmentNotWritableError%20The%20current%20user%20does%20not%20have%20write%20permissions%20to%20the%20targetenvironme%20-%20%E7%9F%A5%E4%B9%8E/v2-b995fba451d29f8c954242b6d399ffba_1440w.jpg&#34;
	
	
	
	loading=&#34;lazy&#34;
	
	
&gt;&lt;/p&gt;
&lt;p&gt;pycharm报错如图&lt;/p&gt;
&lt;p&gt;&lt;img src=&#34;https://Ch-kaiming.github.io/EnvironmentNotWritableError%20The%20current%20user%20does%20not%20have%20write%20permissions%20to%20the%20targetenvironme%20-%20%E7%9F%A5%E4%B9%8E/v2-d2424f62b7249e63c9bc7806b502c518_1440w.jpg&#34;
	
	
	
	loading=&#34;lazy&#34;
	
	
&gt;&lt;/p&gt;
&lt;p&gt;pip下载报错&lt;/p&gt;
&lt;p&gt;错误原因，python虚拟环境base所在文件，没有给予user修改文件的权限。&lt;/p&gt;
&lt;h2 id=&#34;二解决办法&#34;&gt;二、解决办法：
&lt;/h2&gt;&lt;p&gt;1、找到base环境所在文件，右击选择“属性”，再点击“安全”。&lt;/p&gt;
&lt;p&gt;&lt;img src=&#34;https://Ch-kaiming.github.io/EnvironmentNotWritableError%20The%20current%20user%20does%20not%20have%20write%20permissions%20to%20the%20targetenvironme%20-%20%E7%9F%A5%E4%B9%8E/v2-c08269e418b8e6c58203e99d51764986_1440w.jpg&#34;
	
	
	
	loading=&#34;lazy&#34;
	
	
&gt;&lt;/p&gt;
&lt;p&gt;如图可以点击编辑更改权限&lt;/p&gt;
&lt;p&gt;如果不知道文件所在位置可以在Anaconda Prompt输入”coanda env list“查看。&lt;/p&gt;
&lt;p&gt;&lt;img src=&#34;https://Ch-kaiming.github.io/EnvironmentNotWritableError%20The%20current%20user%20does%20not%20have%20write%20permissions%20to%20the%20targetenvironme%20-%20%E7%9F%A5%E4%B9%8E/v2-d0dc2c73e89224d80ec85873d5319b86_1440w.jpg&#34;
	
	
	
	loading=&#34;lazy&#34;
	
	
&gt;&lt;/p&gt;
&lt;p&gt;如图查看虚拟环境所在位置&lt;/p&gt;
&lt;p&gt;2、点击编辑，在组或&lt;a class=&#34;link&#34; href=&#34;https://zhida.zhihu.com/search?content_id=239591744&amp;amp;content_type=Article&amp;amp;match_order=1&amp;amp;q=%E7%94%A8%E6%88%B7%E5%90%8D&amp;amp;zhida_source=entity&#34;  target=&#34;_blank&#34; rel=&#34;noopener&#34;
    &gt;用户名&lt;/a&gt;处选择Users，再将Users的权限都选择允许。&lt;/p&gt;
&lt;p&gt;&lt;img src=&#34;https://Ch-kaiming.github.io/EnvironmentNotWritableError%20The%20current%20user%20does%20not%20have%20write%20permissions%20to%20the%20targetenvironme%20-%20%E7%9F%A5%E4%B9%8E/v2-9dc9be86393e3337c0e4d37057f907ce_1440w.jpg&#34;
	
	
	
	loading=&#34;lazy&#34;
	
	
&gt;&lt;/p&gt;
&lt;p&gt;如图都允许&lt;/p&gt;
&lt;p&gt;3、安装成功。&lt;/p&gt;
&lt;p&gt;&lt;img src=&#34;https://Ch-kaiming.github.io/EnvironmentNotWritableError%20The%20current%20user%20does%20not%20have%20write%20permissions%20to%20the%20targetenvironme%20-%20%E7%9F%A5%E4%B9%8E/v2-7e034ed186bbfe0a50bbc3836746a793_1440w.jpg&#34;
	
	
	
	loading=&#34;lazy&#34;
	
	
&gt;&lt;/p&gt;
&lt;p&gt;安装成功&lt;/p&gt;
</description>
        </item>
        
    </channel>
</rss>
